steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/vitality-api:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/vitality-api:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vitality-api'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/vitality-api:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300s'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--cpu-boost'
      - '--execution-environment'
      - 'gen2'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATABASE_URL=postgresql://postgres:6fk23az4_F@104.199.2.9:5432/vitality_db,JWT_SECRET=969d2205e73cd824d031bd404107845ee6448d0acc7b36b8d1cb3db4ab34dc45,GEMINI_API_KEY=AIzaSyBWZmBaalzL4NCgWSJ98k56GJrAhWcWRzQ,GOOGLE_PLACES_KEY=AIzaSyANvvftQAS3IhffHLTjEahRW50E_18h-hw'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/vitality-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

